### ISSUE TITLE
Java Exeception on Build

### ISSUE THREAD

**Issue by nonsindeads** [Dahlgren/arma3sync-cli#1]
hey,
I have running arma3sync on Ubuntu 16.04 with OpenJDK 9 an I try to build the repository for https.
The repo files are stored in a mounted Amazon Cloude Drive directory. After a few time I get the following exception while processing SHA1

Exeception:
Exception in thread "main" java.lang.IndexOutOfBoundsException: Indexed access out of bounds: 0, 0
        at java.util.Objects.outOfBounds(java.base@9-internal/Objects.java:365)
        at java.util.Objects.checkIndex(java.base@9-internal/Objects.java:436)
        at java.util.Objects.checkIndex(java.base@9-internal/Objects.java:388)
        at java.util.ArrayList.get(java.base@9-internal/ArrayList.java:435)
        at fr.soe.a3s.console.CommandGeneral$RepositoryBuilder.executeError(CommandGeneral.java:121)
        at fr.soe.a3s.console.CommandGeneral$RepositoryBuilder.access$5(CommandGeneral.java:116)
        at fr.soe.a3s.console.CommandGeneral$RepositoryBuilder$4.error(CommandGeneral.java:89)
        at fr.soe.a3s.service.administration.RepositoryBuildProcessor.run(RepositoryBuildProcessor.java:51)
        at fr.soe.a3s.console.CommandGeneral$RepositoryBuilder.run(CommandGeneral.java:94)
        at fr.soe.a3s.console.CommandGeneral.build(CommandGeneral.java:43)
        at fr.soe.a3s.console.CommandLine.build(CommandLine.java:33)
        at fr.soe.a3s.main.ArmA3Sync.runArmA3Sync(ArmA3Sync.java:111)
        at fr.soe.a3s.main.ArmA3Sync.main(ArmA3Sync.java:54)

After some trys iam on 100% but then the next error throws. 

Processing SHA1 signatures... complete: 100 %
Number of SHA1 computed = 958
Processing *.zsync files...
java.io.FileNotFoundException: /mnt/acd/arma3sync/public_ftp/first_repo/@ace/addons/ace_advanced_ballistics.pbo.zsync (Bad address)
        at java.io.FileOutputStream.open0(java.base@9-internal/Native Method)
        at java.io.FileOutputStream.open(java.base@9-internal/FileOutputStream.java:271)
        at java.io.FileOutputStream.<init>(java.base@9-internal/FileOutputStream.java:215)
        at fr.soe.a3s.jazsyncmake.MetaFileMaker.<init>(MetaFileMaker.java:94)
        at fr.soe.a3s.jazsync.Jazsync.make(Jazsync.java:63)
        at fr.soe.a3s.dao.repository.RepositoryZsyncProcessor$1.call(RepositoryZsyncProcessor.java:80)
        at fr.soe.a3s.dao.repository.RepositoryZsyncProcessor$1.call(RepositoryZsyncProcessor.java:1)
        at java.util.concurrent.FutureTask.run(java.base@9-internal/FutureTask.java:266)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(java.base@9-internal/ThreadPoolExecutor.java:1158)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(java.base@9-internal/ThreadPoolExecutor.java:632)
        at java.lang.Thread.run(java.base@9-internal/Thread.java:804)
Number of zsync files generated = 958

**Comment by Dahlgren** [comment]
Are you using the included `Arma3Sync.jar` or a different version?

**Comment by Dahlgren** [comment]
`fr.soe.a3s.main.ArmA3Sync.main` is never called from this codebase. If you are using the standard Arma3Sync CLI commands you should probably ask for help in their forum thread instead, https://forums.bistudio.com/forums/topic/152942-arma3sync-launcher-and-addons-synchronization-software-for-arma-3/

**Comment by nonsindeads** [comment]
THX! for the quick answer.
Whats the difference to your CLI?

**Comment by Dahlgren** [comment]
Mine has some more options for the existing CLI actions and also adds some more such as events and creating new repositories. I haven't updated it to the new 1.6 version of Arma3Sync yet.
